version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: darkblade-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpass
      POSTGRES_DB: darkblade
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: